version: "3"
services:
  app:
    # image: sistema-hospitalario-flask
    build: . 
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    # Otras configuraciones de la aplicación aquí

  mongodb:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=asp_leg
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    # Otras configuraciones de MongoDB aquí
