# Usa la imagen oficial de MongoDB como base
FROM mongo:latest

# Opcional: Personaliza la configuración de MongoDB si es necesario
# COPY ./mongo.conf /etc/mongod.conf

# Expon el puerto de MongoDB (27017) si deseas acceder directamente al servidor de MongoDB
# EXPOSE 27017

# Inicia MongoDB cuando se inicia el contenedor
CMD ["mongod"]
